plot:

##########################################################################Graph Output#########################################################################################################
  
  graph: False #(True or False) Not used!!!
  x_var: 'distance' #('distance','cap','snr','avg_latency')
  y_var: 'cap' #('distance','cap','snr','avg_latency')
  n_bs: 1 #(number of BSs)
  n_s: 59 #(number of simulations)
  type_link: 'downlink_data' #('dowlink_data' or 'uplink_data')

##########################################################################End Graph Output#############################################################################################################

########################################################################Graph Custumize############################################################################################################

  title: 'Capacity x Distance'
  xlabel: 'Distance (Km)'
  ylabel: 'Capacity (Mbps)'
  figsize: [10, 6]
  resolution: 600 # (100, 300 or 600)
  grid: True
  xlim: [0,25]
  ylim: [0,12]
  auto_scale: 'False'  # ('True' or 'False')
  graph_type: 'scatter' #('line', 'bar', 'boxplot', 'scatter' or 'histplot')
  save_as: 'scatter_cap_distance.png'

#####################################################################   End Graph Custumize  ############################################################################################

##########################################################################  Map Output  ##############################################################################################

  
  map: True #(True or False) Not used!!!
  complete: False #(True or False) Not used!!!

######################################################################## End Map Output ###############################################################################


######################################################################## Map Custumize ############################################################################################################
  
  title_map: 'Distribution map of BSs and UEs (20 BSs | 500 UEs)'
  xlabel_map: 'Coordanate X (Km)'
  ylabel_map: 'Coordanate Y (Km)'
  figsize_map: [10, 6]
  resolution_map: 600 # (100, 300 or 600)
  grid_map: True
  xlim_map: [0,30]
  ylim_map: [0,30]
  auto_scale_map: 'False'  # ('True' or 'False')
  save_map_as: 'map_20bss_500ues.png'
  
#######################################################################  End Map Custumize ################################################################################################################
